#!/bin/env python
import numpy as np
import csv

files=[
# Mixed lower and upper probability
"rgbd_people_dataset_beta_01l_3u_headsubcluster",
"rgbd_people_dataset_beta_01l_4u_headsubcluster",
"rgbd_people_dataset_beta_01l_5u_headsubcluster",
"rgbd_people_dataset_beta_01l_6u_headsubcluster",
"rgbd_people_dataset_beta_01l_7u_headsubcluster",
"rgbd_people_dataset_beta_01l_8u_headsubcluster",
"rgbd_people_dataset_beta_05l_3u_headsubcluster",
"rgbd_people_dataset_beta_05l_4u_headsubcluster",
"rgbd_people_dataset_beta_05l_5u_headsubcluster",
"rgbd_people_dataset_beta_05l_6u_headsubcluster",
"rgbd_people_dataset_beta_05l_7u_headsubcluster",
"rgbd_people_dataset_beta_05l_8u_headsubcluster",
"rgbd_people_dataset_beta_10l_3u_headsubcluster",
"rgbd_people_dataset_beta_10l_4u_headsubcluster",
"rgbd_people_dataset_beta_10l_5u_headsubcluster",
"rgbd_people_dataset_beta_10l_6u_headsubcluster",
"rgbd_people_dataset_beta_10l_7u_headsubcluster",
"rgbd_people_dataset_beta_10l_8u_headsubcluster",
"rgbd_people_dataset_beta_20l_3u_headsubcluster",
"rgbd_people_dataset_beta_20l_4u_headsubcluster",
"rgbd_people_dataset_beta_20l_5u_headsubcluster",
"rgbd_people_dataset_beta_20l_6u_headsubcluster",
"rgbd_people_dataset_beta_20l_7u_headsubcluster",
"rgbd_people_dataset_beta_20l_8u_headsubcluster",
"rgbd_people_dataset_beta_30l_3u_headsubcluster",
"rgbd_people_dataset_beta_30l_4u_headsubcluster",
"rgbd_people_dataset_beta_30l_5u_headsubcluster",
"rgbd_people_dataset_beta_30l_6u_headsubcluster",
"rgbd_people_dataset_beta_30l_7u_headsubcluster",
"rgbd_people_dataset_beta_30l_8u_headsubcluster",
## Mixed lower and upper probability
#"rgbd_people_dataset_beta_01l_3u",
#"rgbd_people_dataset_beta_01l_4u",
#"rgbd_people_dataset_beta_01l_5u",
#"rgbd_people_dataset_beta_01l_6u",
#"rgbd_people_dataset_beta_01l_7u",
#"rgbd_people_dataset_beta_01l_8u",
#"rgbd_people_dataset_beta_05l_3u",
#"rgbd_people_dataset_beta_05l_4u",
#"rgbd_people_dataset_beta_05l_5u",
#"rgbd_people_dataset_beta_05l_6u",
#"rgbd_people_dataset_beta_05l_7u",
#"rgbd_people_dataset_beta_05l_8u",
#"rgbd_people_dataset_beta_10l_3u",
#"rgbd_people_dataset_beta_10l_4u",
#"rgbd_people_dataset_beta_10l_5u",
#"rgbd_people_dataset_beta_10l_6u",
#"rgbd_people_dataset_beta_10l_7u",
#"rgbd_people_dataset_beta_10l_8u",
#"rgbd_people_dataset_beta_20l_3u",
#"rgbd_people_dataset_beta_20l_4u",
#"rgbd_people_dataset_beta_20l_5u",
#"rgbd_people_dataset_beta_20l_6u",
#"rgbd_people_dataset_beta_20l_7u",
#"rgbd_people_dataset_beta_20l_8u",
#"rgbd_people_dataset_beta_30l_3u",
#"rgbd_people_dataset_beta_30l_4u",
#"rgbd_people_dataset_beta_30l_5u",
#"rgbd_people_dataset_beta_30l_6u",
#"rgbd_people_dataset_beta_30l_7u",
#"rgbd_people_dataset_beta_30l_8u",
## Change upper prob detection
#'rgbd_people_dataset_beta_30u',
#'rgbd_people_dataset_beta_40u',
#'rgbd_people_dataset_beta_50u',
#'rgbd_people_dataset_beta_60u',
#'rgbd_people_dataset_beta_70u',
#'rgbd_people_dataset_beta_80u',
## Change lower prob detection
#'rgbd_people_dataset_beta_01l',
#'rgbd_people_dataset_beta_05l',
#'rgbd_people_dataset_beta_10l',
#'rgbd_people_dataset_beta_20l',
## Equal prob detection
#'rgbd_people_dataset_beta_30eq',
#'rgbd_people_dataset_beta_40eq',
#'rgbd_people_dataset_beta_50eq',
#'rgbd_people_dataset_beta_60eq',
#'rgbd_people_dataset_beta_70eq',
#'rgbd_people_dataset_beta_80eq',
## Change prob extraction
#'rgbd_people_dataset_beta_30d',
#'rgbd_people_dataset_beta_40d',
#'rgbd_people_dataset_beta_50d',
#'rgbd_people_dataset_beta_60d',
#'rgbd_people_dataset_beta_70d',
#'rgbd_people_dataset_beta_80d',
#'rgbd_people_dataset_beta_90d',
## Change certainty extraction
#'rgbd_people_dataset_beta_001ve',
#'rgbd_people_dataset_beta_005ve',
#'rgbd_people_dataset_beta_009ve',
#'rgbd_people_dataset_beta_013ve',
#'rgbd_people_dataset_beta_017ve',
#'rgbd_people_dataset_beta_021ve',
#'rgbd_people_dataset_beta_025ve',
# No beta tracking
'rgbd_people_dataset_nobeta_30',
'rgbd_people_dataset_nobeta_40',
'rgbd_people_dataset_nobeta_50',
'rgbd_people_dataset_nobeta_60',
'rgbd_people_dataset_nobeta_70',
'rgbd_people_dataset_nobeta_80',
# No beta with different timing to create a tracker
'rgbd_people_dataset_nobeta_1fc',
'rgbd_people_dataset_nobeta_2fc',
'rgbd_people_dataset_nobeta_3fc',
'rgbd_people_dataset_nobeta_4fc',
'rgbd_people_dataset_nobeta_5fc',
'rgbd_people_dataset_nobeta_6fc',
# No beta with different timing to destroy a tracker
'rgbd_people_dataset_nobeta_01fd',
'rgbd_people_dataset_nobeta_03fd',
'rgbd_people_dataset_nobeta_05fd',
'rgbd_people_dataset_nobeta_07fd',
'rgbd_people_dataset_nobeta_09fd',
'rgbd_people_dataset_nobeta_11fd',


'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E9',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E8',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E7',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E6',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E5',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E4',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E3',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E2',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E1',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E0',

'rgbdpd_phd_beta_05l_3u_headsubcluster3_50',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_55',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_60',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_65',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_70',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_75',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_80',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_85',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_95',
#
'rgbdpd_phd_beta_01l_3u_headsubcluster',
'rgbdpd_phd_beta_01l_4u_headsubcluster',
'rgbdpd_phd_beta_01l_5u_headsubcluster',
'rgbdpd_phd_beta_01l_6u_headsubcluster',
'rgbdpd_phd_beta_05l_3u_headsubcluster',
'rgbdpd_phd_beta_05l_4u_headsubcluster',
'rgbdpd_phd_beta_05l_5u_headsubcluster',
'rgbdpd_phd_beta_05l_6u_headsubcluster',
'rgbdpd_phd_beta_1l_3u_headsubcluster',
'rgbdpd_phd_beta_1l_4u_headsubcluster',
'rgbdpd_phd_beta_1l_5u_headsubcluster',
'rgbdpd_phd_beta_1l_6u_headsubcluster',
'rgbdpd_phd_beta_2l_3u_headsubcluster',
'rgbdpd_phd_beta_2l_4u_headsubcluster',
'rgbdpd_phd_beta_2l_5u_headsubcluster',
'rgbdpd_phd_beta_2l_6u_headsubcluster',
'rgbdpd_phd_beta_3l_3u_headsubcluster',
'rgbdpd_phd_beta_3l_4u_headsubcluster',
'rgbdpd_phd_beta_3l_5u_headsubcluster',
'rgbdpd_phd_beta_3l_6u_headsubcluster',

'rgbdpd_phd_beta_01l_3u_headsubcluster7',
'rgbdpd_phd_beta_01l_4u_headsubcluster7',
'rgbdpd_phd_beta_01l_5u_headsubcluster7',
'rgbdpd_phd_beta_01l_6u_headsubcluster7',
'rgbdpd_phd_beta_05l_3u_headsubcluster7',
'rgbdpd_phd_beta_05l_4u_headsubcluster7',
'rgbdpd_phd_beta_05l_5u_headsubcluster7',
'rgbdpd_phd_beta_05l_6u_headsubcluster7',
'rgbdpd_phd_beta_1l_3u_headsubcluster7',
'rgbdpd_phd_beta_1l_4u_headsubcluster7',
'rgbdpd_phd_beta_1l_5u_headsubcluster7',
'rgbdpd_phd_beta_1l_6u_headsubcluster7',
'rgbdpd_phd_beta_2l_3u_headsubcluster7',
'rgbdpd_phd_beta_2l_4u_headsubcluster7',
'rgbdpd_phd_beta_2l_5u_headsubcluster7',
'rgbdpd_phd_beta_2l_6u_headsubcluster7',
'rgbdpd_phd_beta_3l_3u_headsubcluster7',
'rgbdpd_phd_beta_3l_4u_headsubcluster7',
'rgbdpd_phd_beta_3l_5u_headsubcluster7',
'rgbdpd_phd_beta_3l_6u_headsubcluster7',
#
'rgbdpd_phd_beta_01l_3u_headsubcluster3',
'rgbdpd_phd_beta_01l_4u_headsubcluster3',
'rgbdpd_phd_beta_01l_5u_headsubcluster3',
'rgbdpd_phd_beta_01l_6u_headsubcluster3',
'rgbdpd_phd_beta_05l_3u_headsubcluster3',
'rgbdpd_phd_beta_05l_4u_headsubcluster3',
'rgbdpd_phd_beta_05l_5u_headsubcluster3',
'rgbdpd_phd_beta_05l_6u_headsubcluster3',
'rgbdpd_phd_beta_1l_3u_headsubcluster3',
'rgbdpd_phd_beta_1l_4u_headsubcluster3',
'rgbdpd_phd_beta_1l_5u_headsubcluster3',
'rgbdpd_phd_beta_1l_6u_headsubcluster3',
'rgbdpd_phd_beta_2l_3u_headsubcluster3',
'rgbdpd_phd_beta_2l_4u_headsubcluster3',
'rgbdpd_phd_beta_2l_5u_headsubcluster3',
'rgbdpd_phd_beta_2l_6u_headsubcluster3',
'rgbdpd_phd_beta_3l_3u_headsubcluster3',
'rgbdpd_phd_beta_3l_4u_headsubcluster3',
'rgbdpd_phd_beta_3l_5u_headsubcluster3',
'rgbdpd_phd_beta_3l_6u_headsubcluster3',
## Mixed probs
'rgbd_people_dataset_beta_01l_3u_headsubcluster',
'rgbd_people_dataset_beta_01l_4u_headsubcluster',
'rgbd_people_dataset_beta_01l_5u_headsubcluster',
'rgbd_people_dataset_beta_01l_6u_headsubcluster',
'rgbd_people_dataset_beta_01l_7u_headsubcluster',
'rgbd_people_dataset_beta_01l_8u_headsubcluster',
'rgbd_people_dataset_beta_05l_3u_headsubcluster',
'rgbd_people_dataset_beta_05l_4u_headsubcluster',
'rgbd_people_dataset_beta_05l_5u_headsubcluster',
'rgbd_people_dataset_beta_05l_6u_headsubcluster',
'rgbd_people_dataset_beta_05l_7u_headsubcluster',
'rgbd_people_dataset_beta_05l_8u_headsubcluster',
'rgbd_people_dataset_beta_10l_3u_headsubcluster',
'rgbd_people_dataset_beta_10l_4u_headsubcluster',
'rgbd_people_dataset_beta_10l_5u_headsubcluster',
'rgbd_people_dataset_beta_10l_6u_headsubcluster',
'rgbd_people_dataset_beta_10l_7u_headsubcluster',
'rgbd_people_dataset_beta_10l_8u_headsubcluster',
'rgbd_people_dataset_beta_20l_3u_headsubcluster',
'rgbd_people_dataset_beta_20l_4u_headsubcluster',
'rgbd_people_dataset_beta_20l_5u_headsubcluster',
'rgbd_people_dataset_beta_20l_6u_headsubcluster',
'rgbd_people_dataset_beta_20l_7u_headsubcluster',
'rgbd_people_dataset_beta_20l_8u_headsubcluster',
'rgbd_people_dataset_beta_30l_3u_headsubcluster',
'rgbd_people_dataset_beta_30l_4u_headsubcluster',
'rgbd_people_dataset_beta_30l_5u_headsubcluster',
'rgbd_people_dataset_beta_30l_6u_headsubcluster',
'rgbd_people_dataset_beta_30l_7u_headsubcluster',
'rgbd_people_dataset_beta_30l_8u_headsubcluster',
### Change upper prob detection
'rgbd_people_dataset_beta_30u', 
'rgbd_people_dataset_beta_40u', 
'rgbd_people_dataset_beta_50u', 
'rgbd_people_dataset_beta_60u', 
'rgbd_people_dataset_beta_70u', 
'rgbd_people_dataset_beta_80u', 
### Change lower prob detection
'rgbd_people_dataset_beta_01l', 
'rgbd_people_dataset_beta_05l', 
'rgbd_people_dataset_beta_10l', 
'rgbd_people_dataset_beta_20l', 
## Equal prob detection
'rgbd_people_dataset_beta_30eq', 
'rgbd_people_dataset_beta_40eq', 
'rgbd_people_dataset_beta_50eq', 
'rgbd_people_dataset_beta_60eq', 
'rgbd_people_dataset_beta_70eq', 
'rgbd_people_dataset_beta_80eq', 
## Change prob extraction
'rgbd_people_dataset_beta_30d',
'rgbd_people_dataset_beta_40d',
'rgbd_people_dataset_beta_50d',
'rgbd_people_dataset_beta_60d',
'rgbd_people_dataset_beta_70d',
'rgbd_people_dataset_beta_80d',
'rgbd_people_dataset_beta_90d',
## Change certainty extraction
'rgbd_people_dataset_beta_001ve',
'rgbd_people_dataset_beta_005ve',
'rgbd_people_dataset_beta_009ve',
'rgbd_people_dataset_beta_013ve',
'rgbd_people_dataset_beta_017ve',
'rgbd_people_dataset_beta_021ve',
'rgbd_people_dataset_beta_025ve',
### No beta tracking
'rgbd_people_dataset_nobeta_30', 
'rgbd_people_dataset_nobeta_40', 
'rgbd_people_dataset_nobeta_50', 
'rgbd_people_dataset_nobeta_60', 
'rgbd_people_dataset_nobeta_70', 
'rgbd_people_dataset_nobeta_80', 
### No beta with different timing to create a tracker
'rgbd_people_dataset_nobeta_1fc', 
'rgbd_people_dataset_nobeta_2fc', 
'rgbd_people_dataset_nobeta_3fc', 
'rgbd_people_dataset_nobeta_4fc', 
'rgbd_people_dataset_nobeta_5fc', 
'rgbd_people_dataset_nobeta_6fc', 
### No beta with different timing to destroy a tracker
'rgbd_people_dataset_nobeta_01fd', 
'rgbd_people_dataset_nobeta_03fd', 
'rgbd_people_dataset_nobeta_05fd', 
'rgbd_people_dataset_nobeta_07fd', 
'rgbd_people_dataset_nobeta_09fd', 
'rgbd_people_dataset_nobeta_11fd', 
]

titles=[
"Lower 1% upper 30%",
"Lower 1% upper 40%",
"Lower 1% upper 50%",
"Lower 1% upper 60%",
"Lower 1% upper 70%",
"Lower 1% upper 80%",
"Lower 5% upper 30%",
"Lower 5% upper 40%",
"Lower 5% upper 50%",
"Lower 5% upper 60%",
"Lower 5% upper 70%",
"Lower 5% upper 80%",
"Lower 10% upper 30%",
"Lower 10% upper 40%",
"Lower 10% upper 50%",
"Lower 10% upper 60%",
"Lower 10% upper 70%",
"Lower 10% upper 80%",
"Lower 20% upper 30%",
"Lower 20% upper 40%",
"Lower 20% upper 50%",
"Lower 20% upper 60%",
"Lower 20% upper 70%",
"Lower 20% upper 80%",
"Lower 30% upper 30%",
"Lower 30% upper 40%",
"Lower 30% upper 50%",
"Lower 30% upper 60%",
"Lower 30% upper 70%",
"Lower 30% upper 80%",
#'Beta tracker with 30% upper certainty',
#'Beta tracker with 40% upper certainty',
#'Beta tracker with 50% upper certainty',
#'Beta tracker with 60% upper certainty',
#'Beta tracker with 70% upper certainty',
#'Beta tracker with 80% upper certainty',
#'Beta tracker with 1% lower certainty',
#'Beta tracker with 5% lower certainty',
#'Beta tracker with 10% lower certainty',
#'Beta tracker with 20% lower certainty',
#'Beta tracker with 30% threshold certainty',
#'Beta tracker with 40% threshold certainty',
#'Beta tracker with 50% threshold certainty',
#'Beta tracker with 60% threshold certainty',
#'Beta tracker with 70% threshold certainty',
#'Beta tracker with 80% threshold certainty',
#'Beta tracker with 30% person probability',
#'Beta tracker with 40% person probability',
#'Beta tracker with 50% person probability',
#'Beta tracker with 60% person probability',
#'Beta tracker with 70% person probability',
#'Beta tracker with 80% person probability',
#'Beta tracker with 90% person probability',
#'Beta tracker with 0.001 person probability variance',
#'Beta tracker with 0.005 person probability variance',
#'Beta tracker with 0.009 person probability variance',
#'Beta tracker with 0.013 person probability variance',
#'Beta tracker with 0.017 person probability variance',
#'Beta tracker with 0.021 person probability variance',
#'Beta tracker with 0.025 person probability variance',
'Normal tracker with 30% certainty',
'Normal tracker with 40% certainty',
'Normal tracker with 50% certainty',
'Normal tracker with 60% certainty',
'Normal tracker with 70% certainty',
'Normal tracker with 80% certainty',
'Normal tracker with 1 frame tracker creation',
'Normal tracker with 2 frames tracker creation',
'Normal tracker with 3 frames tracker creation',
'Normal tracker with 4 frames tracker creation',
'Normal tracker with 5 frames tracker creation',
'Normal tracker with 6 frames tracker creation',
'Normal tracker with 1 frame tracker deletion',
'Normal tracker with 3 frames tracker deletion',
'Normal tracker with 5 frames tracker deletion',
'Normal tracker with 7 frames tracker deletion',
'Normal tracker with 9 frames tracker deletion',
'Normal tracker with 11 frames tracker deletion',

'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E9.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E8.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E7.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E6.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E5.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E4.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E3.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E2.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E1.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90_E0.csv',

'rgbdpd_phd_beta_05l_3u_headsubcluster3_50.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_55.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_60.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_65.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_70.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_75.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_80.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_85.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_90.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3_95.csv',
#
'rgbdpd_phd_beta_01l_3u_headsubcluster.csv',
'rgbdpd_phd_beta_01l_4u_headsubcluster.csv',
'rgbdpd_phd_beta_01l_5u_headsubcluster.csv',
'rgbdpd_phd_beta_01l_6u_headsubcluster.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster.csv',
'rgbdpd_phd_beta_05l_4u_headsubcluster.csv',
'rgbdpd_phd_beta_05l_5u_headsubcluster.csv',
'rgbdpd_phd_beta_05l_6u_headsubcluster.csv',
'rgbdpd_phd_beta_1l_3u_headsubcluster.csv',
'rgbdpd_phd_beta_1l_4u_headsubcluster.csv',
'rgbdpd_phd_beta_1l_5u_headsubcluster.csv',
'rgbdpd_phd_beta_1l_6u_headsubcluster.csv',
'rgbdpd_phd_beta_2l_3u_headsubcluster.csv',
'rgbdpd_phd_beta_2l_4u_headsubcluster.csv',
'rgbdpd_phd_beta_2l_5u_headsubcluster.csv',
'rgbdpd_phd_beta_2l_6u_headsubcluster.csv',
'rgbdpd_phd_beta_3l_3u_headsubcluster.csv',
'rgbdpd_phd_beta_3l_4u_headsubcluster.csv',
'rgbdpd_phd_beta_3l_5u_headsubcluster.csv',
'rgbdpd_phd_beta_3l_6u_headsubcluster.csv',

'rgbdpd_phd_beta_01l_3u_headsubcluster7.csv',
'rgbdpd_phd_beta_01l_4u_headsubcluster7.csv',
'rgbdpd_phd_beta_01l_5u_headsubcluster7.csv',
'rgbdpd_phd_beta_01l_6u_headsubcluster7.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster7.csv',
'rgbdpd_phd_beta_05l_4u_headsubcluster7.csv',
'rgbdpd_phd_beta_05l_5u_headsubcluster7.csv',
'rgbdpd_phd_beta_05l_6u_headsubcluster7.csv',
'rgbdpd_phd_beta_1l_3u_headsubcluster7.csv',
'rgbdpd_phd_beta_1l_4u_headsubcluster7.csv',
'rgbdpd_phd_beta_1l_5u_headsubcluster7.csv',
'rgbdpd_phd_beta_1l_6u_headsubcluster7.csv',
'rgbdpd_phd_beta_2l_3u_headsubcluster7.csv',
'rgbdpd_phd_beta_2l_4u_headsubcluster7.csv',
'rgbdpd_phd_beta_2l_5u_headsubcluster7.csv',
'rgbdpd_phd_beta_2l_6u_headsubcluster7.csv',
'rgbdpd_phd_beta_3l_3u_headsubcluster7.csv',
'rgbdpd_phd_beta_3l_4u_headsubcluster7.csv',
'rgbdpd_phd_beta_3l_5u_headsubcluster7.csv',
'rgbdpd_phd_beta_3l_6u_headsubcluster7.csv',
#
'rgbdpd_phd_beta_01l_3u_headsubcluster3.csv',
'rgbdpd_phd_beta_01l_4u_headsubcluster3.csv',
'rgbdpd_phd_beta_01l_5u_headsubcluster3.csv',
'rgbdpd_phd_beta_01l_6u_headsubcluster3.csv',
'rgbdpd_phd_beta_05l_3u_headsubcluster3.csv',
'rgbdpd_phd_beta_05l_4u_headsubcluster3.csv',
'rgbdpd_phd_beta_05l_5u_headsubcluster3.csv',
'rgbdpd_phd_beta_05l_6u_headsubcluster3.csv',
'rgbdpd_phd_beta_1l_3u_headsubcluster3.csv',
'rgbdpd_phd_beta_1l_4u_headsubcluster3.csv',
'rgbdpd_phd_beta_1l_5u_headsubcluster3.csv',
'rgbdpd_phd_beta_1l_6u_headsubcluster3.csv',
'rgbdpd_phd_beta_2l_3u_headsubcluster3.csv',
'rgbdpd_phd_beta_2l_4u_headsubcluster3.csv',
'rgbdpd_phd_beta_2l_5u_headsubcluster3.csv',
'rgbdpd_phd_beta_2l_6u_headsubcluster3.csv',
'rgbdpd_phd_beta_3l_3u_headsubcluster3.csv',
'rgbdpd_phd_beta_3l_4u_headsubcluster3.csv',
'rgbdpd_phd_beta_3l_5u_headsubcluster3.csv',
'rgbdpd_phd_beta_3l_6u_headsubcluster3.csv',
## Mixed probs
'rgbd_people_dataset_beta_01l_3u_headsubcluster.csv',
'rgbd_people_dataset_beta_01l_4u_headsubcluster.csv',
'rgbd_people_dataset_beta_01l_5u_headsubcluster.csv',
'rgbd_people_dataset_beta_01l_6u_headsubcluster.csv',
'rgbd_people_dataset_beta_01l_7u_headsubcluster.csv',
'rgbd_people_dataset_beta_01l_8u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_3u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_4u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_5u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_6u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_7u_headsubcluster.csv',
'rgbd_people_dataset_beta_05l_8u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_3u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_4u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_5u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_6u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_7u_headsubcluster.csv',
'rgbd_people_dataset_beta_10l_8u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_3u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_4u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_5u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_6u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_7u_headsubcluster.csv',
'rgbd_people_dataset_beta_20l_8u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_3u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_4u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_5u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_6u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_7u_headsubcluster.csv',
'rgbd_people_dataset_beta_30l_8u_headsubcluster.csv',
### Change upper prob detection
'rgbd_people_dataset_beta_30u.csv', 
'rgbd_people_dataset_beta_40u.csv', 
'rgbd_people_dataset_beta_50u.csv', 
'rgbd_people_dataset_beta_60u.csv', 
'rgbd_people_dataset_beta_70u.csv', 
'rgbd_people_dataset_beta_80u.csv', 
### Change lower prob detection
'rgbd_people_dataset_beta_01l.csv', 
'rgbd_people_dataset_beta_05l.csv', 
'rgbd_people_dataset_beta_10l.csv', 
'rgbd_people_dataset_beta_20l.csv', 
## Equal prob detection
'rgbd_people_dataset_beta_30eq.csv', 
'rgbd_people_dataset_beta_40eq.csv', 
'rgbd_people_dataset_beta_50eq.csv', 
'rgbd_people_dataset_beta_60eq.csv', 
'rgbd_people_dataset_beta_70eq.csv', 
'rgbd_people_dataset_beta_80eq.csv', 
## Change prob extraction
'rgbd_people_dataset_beta_30d.csv',
'rgbd_people_dataset_beta_40d.csv',
'rgbd_people_dataset_beta_50d.csv',
'rgbd_people_dataset_beta_60d.csv',
'rgbd_people_dataset_beta_70d.csv',
'rgbd_people_dataset_beta_80d.csv',
'rgbd_people_dataset_beta_90d.csv',
## Change certainty extraction
'rgbd_people_dataset_beta_001ve.csv',
'rgbd_people_dataset_beta_005ve.csv',
'rgbd_people_dataset_beta_009ve.csv',
'rgbd_people_dataset_beta_013ve.csv',
'rgbd_people_dataset_beta_017ve.csv',
'rgbd_people_dataset_beta_021ve.csv',
'rgbd_people_dataset_beta_025ve.csv',
### No beta tracking
'rgbd_people_dataset_nobeta_30.csv', 
'rgbd_people_dataset_nobeta_40.csv', 
'rgbd_people_dataset_nobeta_50.csv', 
'rgbd_people_dataset_nobeta_60.csv', 
'rgbd_people_dataset_nobeta_70.csv', 
'rgbd_people_dataset_nobeta_80.csv', 
### No beta with different timing to create a tracker
'rgbd_people_dataset_nobeta_1fc.csv', 
'rgbd_people_dataset_nobeta_2fc.csv', 
'rgbd_people_dataset_nobeta_3fc.csv', 
'rgbd_people_dataset_nobeta_4fc.csv', 
'rgbd_people_dataset_nobeta_5fc.csv', 
'rgbd_people_dataset_nobeta_6fc.csv', 
### No beta with different timing to destroy a tracker
'rgbd_people_dataset_nobeta_01fd.csv', 
'rgbd_people_dataset_nobeta_03fd.csv', 
'rgbd_people_dataset_nobeta_05fd.csv', 
'rgbd_people_dataset_nobeta_07fd.csv', 
'rgbd_people_dataset_nobeta_09fd.csv', 
'rgbd_people_dataset_nobeta_11fd.csv', 
]

for i,f in enumerate(files):
    data = np.array([[float(x) for x in row] for row in csv.reader(open('data/' + f + '.csv', 'r'))])
    print titles[i], 'MOTP:', data[-1,9], 'MOTA:', data[-1,10]*100.0, 'Miss detection rate:', data[-1,11]*100.0, 'False positves rate:', data[-1,12]*100.0, 'Miss matches:', data[-1,19]
